polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'  # adding a namespace to identify the urls related to app
'''
urlpatterns = [
        # /polls/
        url(r'^$', views.index, name='index'),
        # /polls/5/
        url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
        # /polls/5/results/
        url(r'(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
        # /polls/5/vote/
        url(r'(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
        ]
'''
urlpatterns = [
        # /polls/
        url(r'^$', views.IndexView.as_view(), name='index'),
        # /polls/5/
        url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
        # /polls/5/results/
        url(r'(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
        # /polls/5/vote/
        url(r'(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
        ]

project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('public.urls')),
    url(r'^analysis/', include('staff.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^staff/', admin.site.urls),
    url(r'^admin/', admin.site.urls),
]

staff/urls.py
from django.conf.urls import url

from . import views

app_name = 'staff'  # adding namespace to identify

urlpatterns = [
        # /analysis/ if app but home page is this so /
        url(r'^$', views.analysis, name='analysis'),
        url(r'^api/data/$', views.getdataforchart, name="data"),
        # url(r'^login/$', views.loginView, name='login'),
        # url(r'^authenticate/$', views.authenticateView, name='authenticate'),
        # url(r'^login/valid/$', views.validLoginView, name='validLogin'),
        # url(r'^login/invalid/$', views.invalidLoginView, name='invalidLogin'),
        # url(r'^logout/$', views.logoutView, name='logout'),
        # url(r'^signup/$', views.signupView, name='signup'),
        # url(r'^main/$', views.publicmainView, name='publicmain'),
        # url(r'^ajaxSearch/$', views.searchView, name='search'),
        ]

polls/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone

import datetime


# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    # like doc string which returns
    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()   # code modified after test
        return timezone.now() - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

staff/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Transaction(models.Model):

      date= models.DateTimeField()

      pid= models.CharField(max_length=20)
      userid = models.CharField(max_length=20)
        issuedby= models.CharField(max_length=100)

polls/views.py
from django.shortcuts import render, get_object_or_404
from .models import Question, Choice

# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from django.utils import timezone
# from django.template import loader if alternate method used

'''
def index(request):
    latestQuestionList = Question.objects.order_by('-pub_date')[:5]

    context = {
        'latestQuestionList': latestQuestionList,
    }

    ''''''
    alternate method
    template = loader.get_template('polls/index.html')

        return HttpResponse(template.render(context, request))
    ''''''
    return render(request, 'polls/index.html', context)


def detail(request, question_id):
    ''''''long method
      try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'polls/detail.html', {'question': question})
    ''''''

    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})


    def results(request, question_id):
        question = get_object_or_404(Question, pk=question_id)
        return render(request, 'polls/results.html', {'question': question})



'''


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latestQuestionList'
    #  index template outputs no polls are available is no Question

    def get_queryset(self):
        #  returns that of time past only
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    # since the model is Question default variable in question

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):  # POST['choice'] raies key error
        # redisplay list
        return render(request, 'polls/detail.html', {'question': question, 'error_message': "you didnt select a choice."})
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # prevent multiple voting by redirect
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

staff/views.py
from django.shortcuts import render
from django.http import JsonResponse
from public.models import OfficeData
from django.utils import timezone

# Create your views here.


def analysis(request):
    return render(request, 'staff/analyse.html', {})


def getdataforchart(request):
    year = timezone.now().year
    labels = []
    sales = []
    for i in range(year-10, year+1):
        labels += [i]
        valid = OfficeData.objects.filter(boughtdate__year=i)
        default = sum([d.boughtprice*d.quantity for d in valid])
        sales += [default]

    data = {
            "labels": labels,
            "defaultData": sales,
    }
    return JsonResponse(data)

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
{% if error_message %}<p><strong>{{ error_message}}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all  %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id}}"/>
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br/>
    {% endfor %}
    <input type="submit" value="Vote"/>
</form>

polls/templates/polls/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
{% if latestQuestionList %}
    <ul>
    {% for question in latestQuestionList %}
        <li><a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a></li>
    {% endfor %}
    </ul>
{% else %}
<p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }}
    vote{{ choice.votes|pluralize}}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

staff/templates/staff/analyse.html
{% extends "staff/header1.html" %}

{% block title %}Analysis {% endblock title %}
{% block jquery %}
<script>
var endpoint = "{% url 'staff:data' %}";
var defaultData = [];
var labels = [];
var labesl
$.ajax({
    method:"GET",
    url: endpoint,
    success: function(data){
        labels = data.labels;
        defaultData = data.defaultData;
        var ctx = document.getElementById("myChart");
        var myChart = new Chart(ctx, {
            type: 'line',
            data: {
                labels: labels,
                datasets: [{
                    label: 'Total annual purchase of Office',
                    data: defaultData,
                    backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',],
                }],

            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero:true
                        }
                    }]
                }
            }
        });
    },
    error: function(error_data){
        console.log(error_data);
    }
});

</script>
{% endblock jquery %}

{% block content %}
<canvas id="myChart" width="250" height="80"></canvas>




{% endblock content %}

staff/templates/staff/header1.html
<!--<!DOCTYPE html>
<html lang="en">
<head>
  	<title></title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
</head>
<body id="{% block body_id %}{% endblock body_id %}" class="{% block body_class %}{% endblock body_class %}">
	<div id="body">
      <div class="topHeader">
          {% block upperheading %} {% endblock upperheading %}
	  </div>
	  <div class="notificationArea">
            {% block fornotification%} {% endblock fornotification %}
		</div>
		<div class="activityArea">
            {% block foractivity %} {% endblock foractivity%}
          </div>

           <div class="searchArea">
            {% block forsearch%} {% endblock forsearch%}
          </div>

           <div class="dashboardArea">
            {% block fordashboard%} {% endblock fordashboard%}
          </div>

		 </div>
</body>
</html>
-->
<!DOCTYPE html>
<html lang="en">

<head>
	<title>{% block title %}{% endblock title%}</title>
	<meta charset="utf-8" />
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type = "text/css"/>
	<meta name="viewport" content = "width=device-width, initial-scale=1.0">

	<style type="text/css">
		html,
		body {
		  height:100%
		}
	</style>
	{% block stylesheet %}{% endblock stylesheet %}
</head>

<body class="body" style="background-color:#f6f6f6">
	<div class="container-fluid" style="min-height:95%; ">
		<div class="row">
			<nav class="navbar navbar-inverse" style="background-color:#3c6772">
  			<div class="container-fluid">
    		<!-- Brand and toggle get grouped for better mobile display -->
    		<div class="navbar-header">
      		<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        		<span class="sr-only">Toggle navigation</span>
        		<span class="icon-bar"></span>
        		<span class="icon-bar"></span>
        		<span class="icon-bar"></span>
      		</button>
      		<a class="navbar-brand" href="{%url 'public:publicmain'%}">Office Purchase Analysis</a>
    		</div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      		<ul class="nav navbar-nav">
        		<li><a>Welcome {{ username }}</a><span class="sr-only">(current)</span></a></li>
        <li></li>
		<li></li>
      </ul>
	  <br><br><hr>
    	</div><!-- /.navbar-collapse -->
  		</div><!-- /.container-fluid -->
		</nav>
		</div>
		<div class="row content">
			{% block content %}{% endblock content %}

		</div>
	</div>

	<footer>
		<div class="container-fluid" style='margin-left:15px'>
			<p><a href="#" target="blank">Contact</a> | <a href="#" target="blank">LinkedIn</a> | <a href="#" target="blank">Twitter</a> | <a href="#" target="blank">Google+</a></p>
		</div>
	</footer>


	<script src="{% static 'js/jquery-1.9.1.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/Chart.min.js' %}"></script>
	{% block jquery %}{% endblock jquery %}
</body>

</html>

staff/templates/staff/includes/snippet.html
{% block content %}
<p> Just a include snippet</p>
{% endblock %}